[internal]

exten => 7000,1,Answer()
 same => n,Playback(custom/balance-query/welcome)
 same => n,Read(MSISDN,custom/balance-query/enter-mobile-number,11)

 ; Print the entered number
 same => n,AGI(agi://127.0.0.1/balance.agi?msisdn=${MSISDN})

 ; Check if it is exactly 11 digits
 same => n,GotoIf($[${LEN(${MSISDN})}=11]?valid:invalid)

 same => n(valid),NoOp(Valid number)
 same => n,Playback(custom/balance-query/goodbye)
 same => n,Hangup()

 same => n(invalid),Playback(custom/balance-query/invalid-number)
 same => n,Hangup()
