[internal]

exten => 7000,1,Answer()
 same => n,Playback(custom/balance-query/welcome)
 same => n,Read(MSISDN,custom/balance-query/enter-mobile-number,11)
 same => n,AGI(agi://127.0.0.1:4573/balance.agi?msisdn=${MSISDN})
 same => n,Hangup()