;==========================
; Authentication
;==========================

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[6001-auth]
type=auth
auth_type=userpass
username=6001
password=1234

;==========================
; Address Of Record
;==========================

[6001]
type=aor
max_contacts=1

;==========================
; Endpoint
;==========================

[6001]
type=endpoint
transport=transport-udp
context=internal

disallow=all
allow=ulaw

auth=6001-auth
aors=6001
